/**
 * /read reads documents, summarizes them, and refuses what it cannot read.
 *
 * Found by the CEO on the Windows clone, 2026-09-07: /read on a PDF reported
 * success and returned decoded binary — a green chip and garbage. The Matrix
 * could already extract PDFs, but host_os may not reach into another block, so
 * extraction moved to the kernel (src/kernel/extract.cjs) and /read uses it.
 * A format the extractor cannot read is refused with a remedy (§08), never
 * "read". "read + document" is one command: the summary first, the text behind it.
 */
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import fs from 'fs';
import os from 'os';
import path from 'path';
import express from 'express';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const createFsRouter = require('../src/blocks/host_os/api/fs.cjs');
const extract = require('../src/kernel/extract.cjs');

// A real PDF, generated by jspdf (already in node_modules).
const REAL_PDF = async (text) => {
  const { jsPDF } = require('jspdf');
  const doc = new jsPDF();
  doc.text(text, 20, 30);
  return Buffer.from(doc.output('arraybuffer'));
};

// A hand-built PDF whose xref pdf.js rejects ("bad XRef entry") — the
// damaged-document fixture. It parsed once in isolation and not under the
// route, which is exactly the kind of file an operator will feed /read.
const BROKEN_PDF = () => {
  const text = 'BT /F1 18 Tf 40 700 Td (The keyslot bridge ships first) Tj ET';
  const objs = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>',
    `<< /Length ${text.length} >>\nstream\n${text}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];
  let out = '%PDF-1.4\n'; const offsets = [];
  objs.forEach((o, i) => { offsets.push(out.length); out += `${i + 1} 0 obj\n${o}\nendobj\n`; });
  const xref = out.length;
  out += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n` + offsets.map(o => String(o).padStart(10, '0') + ' 00000 n \n').join('');
  out += `trailer\n<< /Size ${objs.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return Buffer.from(out, 'latin1');
};

let root, servers, llm;
const listen = (router) => new Promise((resolve) => {
  const a = express(); a.use(express.json()); a.use('/api', router);
  const server = a.listen(0, '127.0.0.1', () => resolve({ server, port: server.address().port }));
});
const read = async (port, filePath, extra = {}) => {
  const r = await fetch(`http://127.0.0.1:${port}/api/fs/read`, {
    method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ filePath, ...extra }),
  });
  return { status: r.status, body: await r.json() };
};
async function mount({ withModel = true } = {}) {
  llm = withModel ? vi.fn(async () => 'SUMMARY: the keyslot bridge ships first.') : null;
  const router = createFsRouter({ isVercel: false, WORKSPACE: root, HOME_ROOT: root, VAULT_ROOT: path.join(root, 'Vault'), kernelLLM: llm, getDataFile: (n) => path.join(root, n) });
  const h = await listen(router); servers.push(h.server); return h.port;
}

beforeEach(() => { root = fs.mkdtempSync(path.join(os.tmpdir(), 'aeon-read-')); servers = []; });
afterEach(() => { for (const s of servers) { try { s.close(); } catch {} } try { fs.rmSync(root, { recursive: true, force: true }); } catch {} });

describe('/read on a document', () => {
  it('a PDF comes back as its words, with a summary', async () => {
    fs.writeFileSync(path.join(root, 'memo.pdf'), await REAL_PDF('The keyslot bridge ships first'));
    const port = await mount();
    const r = await read(port, 'memo.pdf');
    expect(r.status).toBe(200);
    expect(r.body.kind).toBe('document');
    expect(r.body.content).toMatch(/keyslot bridge ships first/);
    expect(r.body.content).not.toMatch(/%PDF|endobj/);
    expect(r.body.summary).toMatch(/^SUMMARY/);
    expect(r.body.text).toMatch(/^SUMMARY/);             // what the terminal prints
    expect(llm.mock.calls[0][0]).toMatch(/keyslot bridge ships first/); // the model saw the words
  });

  it('HTML is read as text', async () => {
    fs.writeFileSync(path.join(root, 'page.html'), '<html><body><h1>Title</h1><p>The vault needs <b>both</b> halves.</p></body></html>');
    const port = await mount();
    const r = await read(port, 'page.html');
    expect(r.status).toBe(200);
    expect(r.body.content).toMatch(/The vault needs both halves/);
    expect(r.body.content).not.toMatch(/<p>/);
  });

  it('a plain text file still works as before, summarized when a model exists', async () => {
    fs.writeFileSync(path.join(root, 'notes.md'), '# Notes\nMove both or neither.');
    const port = await mount();
    const r = await read(port, 'notes.md');
    expect(r.status).toBe(200);
    expect(r.body.kind).toBe('text');
    expect(r.body.lines).toBe(2);
    expect(r.body.summary).toBeTruthy();
  });

  it('without a model, the text is the answer and the response says why', async () => {
    fs.writeFileSync(path.join(root, 'notes.md'), '# Notes\nMove both or neither.');
    const port = await mount({ withModel: false });
    const r = await read(port, 'notes.md');
    expect(r.status).toBe(200);
    expect(r.body.summary).toBeNull();
    expect(r.body.summaryReason).toMatch(/no model/i);
    expect(r.body.text).toMatch(/Move both or neither/);
  });

  it('summarize:false returns the text only and spends nothing', async () => {
    fs.writeFileSync(path.join(root, 'notes.md'), 'plain');
    const port = await mount();
    const r = await read(port, 'notes.md', { summarize: false });
    expect(r.body.summary).toBeNull();
    expect(llm).not.toHaveBeenCalled();
  });
});

describe('/read refuses what it cannot read', () => {
  it('a PNG is refused with a remedy, not returned as bytes', async () => {
    fs.writeFileSync(path.join(root, 'shot.png'), Buffer.from([0x89, 0x50, 0x4e, 0x47, 0, 0, 0, 0]));
    const port = await mount();
    const r = await read(port, 'shot.png');
    expect(r.status).toBe(415);
    expect(r.body.error).toMatch(/not a text or document format/);
    expect(r.body.remedy).toMatch(/File Manager/);
    expect(r.body.content).toBeUndefined();
    expect(llm).not.toHaveBeenCalled();
  });

  it('a damaged PDF is refused with a remedy, not a 500', async () => {
    fs.writeFileSync(path.join(root, 'broken.pdf'), BROKEN_PDF());
    const port = await mount();
    const r = await read(port, 'broken.pdf');
    // pdf.js may recover some hand-built files; either outcome must be honest.
    if (r.status === 200) { expect(r.body.content).toMatch(/keyslot bridge/); return; }
    expect(r.status).toBe(422);
    expect(r.body.error).toMatch(/Could not read broken\.pdf/);
    expect(r.body.remedy).toMatch(/export it again|copy its text/);
  });

  it('a missing file still says where it looked', async () => {
    const port = await mount();
    const r = await read(port, 'nope.md');
    expect(r.status).toBe(404);
    expect(r.body.error).toMatch(/Not found/);
  });
});

describe('the kernel extractor', () => {
  it('classifies by extension', () => {
    expect(extract.kindOf('a.pdf')).toBe('document');
    expect(extract.kindOf('a.md')).toBe('text');
    expect(extract.kindOf('a.png')).toBe('binary');
  });
  it('the Matrix uses the same extractor, not its own copy', () => {
    const src = fs.readFileSync(path.join(path.dirname(new URL(import.meta.url).pathname), '..', 'src/blocks/aeon_matrix/api/_lib.cjs'), 'utf8');
    expect(src).toMatch(/require\('\.\.\/\.\.\/\.\.\/kernel\/extract\.cjs'\)/);
    expect(src).not.toMatch(/require\('pdf-parse'\)/);
  });
});
