// AUTO-GENERATED by scripts/gen-vercel-mounts.cjs — do not edit by hand
// Vercel NFT requires static require paths; this file is regenerated at build time.

// depsFor(blockId) lets the caller scope dependencies per manifest, exactly as
// the local block host does. Cloud mode used to receive one flat 13-key object
// shared by every block: manifest permissions governed nothing in cloud, and
// blocks that legitimately expected other deps got undefined. dashboard/chat
// destructured getDailyCost, called it on every AI message, threw TypeError and
// answered HTTP 500 — the primary chat feature, broken in production.
global.mountStaticBlocks = function(app, deps, depsFor) {
  const mounts = [
    { block: 'activity', file: '../src/blocks/activity/api/analytics.cjs' },
    { block: 'activity', file: '../src/blocks/activity/api/token-analytics.cjs' },
    { block: 'aeon_matrix', file: '../src/blocks/aeon_matrix/api/cloudvault.cjs' },
    { block: 'aeon_matrix', file: '../src/blocks/aeon_matrix/api/index.cjs' },
    { block: 'aeon_matrix', file: '../src/blocks/aeon_matrix/api/ingest.cjs' },
    { block: 'aeon_matrix', file: '../src/blocks/aeon_matrix/api/retrieve.cjs' },
    { block: 'aeon_matrix', file: '../src/blocks/aeon_matrix/api/sync.cjs' },
    { block: 'council', file: '../src/blocks/council/api/index.cjs' },
    { block: 'dashboard', file: '../src/blocks/dashboard/api/audit.js' },
    { block: 'dashboard', file: '../src/blocks/dashboard/api/chat-stream.cjs' },
    { block: 'dashboard', file: '../src/blocks/dashboard/api/chat.cjs' },
    { block: 'dashboard', file: '../src/blocks/dashboard/api/health.js' },
    { block: 'dashboard', file: '../src/blocks/dashboard/api/pipeline-metrics.js' },
    { block: 'deep_research', file: '../src/blocks/deep_research/api/index.cjs' },
    { block: 'files', file: '../src/blocks/files/api/fs/read.js' },
    { block: 'files', file: '../src/blocks/files/api/fs/write.js' },
    { block: 'files', file: '../src/blocks/files/api/notes.js' },
    { block: 'fleet_control', file: '../src/blocks/fleet_control/api/hwfit.cjs' },
    { block: 'fleet_control', file: '../src/blocks/fleet_control/api/local-status.js' },
    { block: 'fleet_control', file: '../src/blocks/fleet_control/api/missions.cjs' },
    { block: 'fleet_control', file: '../src/blocks/fleet_control/api/telemetry.js' },
    { block: 'master', file: '../src/blocks/master/api/master.cjs' },
    { block: 'orion_search', file: '../src/blocks/orion_search/api/orion.cjs' },
    { block: 'resume_grader', file: '../src/blocks/resume_grader/api/grade-resume.js' },
    { block: 'security', file: '../src/blocks/security/api/guardian.cjs' },
    { block: 'security', file: '../src/blocks/security/api/security.js' },
    { block: 'settings', file: '../src/blocks/settings/api/connections.js' },
    { block: 'settings', file: '../src/blocks/settings/api/connectivity.js' },
    { block: 'settings', file: '../src/blocks/settings/api/model-scan.js' },
    { block: 'settings', file: '../src/blocks/settings/api/settings.js' },
    { block: 'writer', file: '../src/blocks/writer/api/writer.js' },
    { block: 'writer', file: '../src/blocks/writer/api/writer2.cjs' },
  ];
  const resolve = typeof depsFor === 'function' ? depsFor : () => deps;
  // Mirror blockHost.cjs signature detection: factory (deps)=>router files
  // must have their RETURNED router mounted — calling them as (app, deps)
  // silently discards the router (found 2026-07-16: /api/research/* 404 on web).
  for (const m of mounts) {
    try {
      const factory = require(m.file);
      if (typeof factory !== 'function') continue;
      const scoped = resolve(m.block) || deps;
      if (typeof factory.use === 'function' && Array.isArray(factory.stack)) {
        app.use('/api', factory);                 // exported a bare router
      } else if (factory.length === 1) {
        const result = factory(scoped);           // factory pattern
        if (result && typeof result.use === 'function') app.use('/api', result);
      } else {
        factory(app, scoped);                     // plugin pattern
      }
    } catch(e) { console.error('[VERCEL] Static mount error (' + m.file + '):', e.message); }
  }
};

module.exports = require('../server.cjs');
