// AUTO-GENERATED by scripts/gen-vercel-mounts.cjs — do not edit by hand
// Vercel NFT requires static require paths; this file is regenerated at build time.

global.mountStaticBlocks = function(app, deps) {
  const mounts = [
    '../src/blocks/activity/api/analytics.cjs',
    '../src/blocks/activity/api/token-analytics.cjs',
    '../src/blocks/aeon_matrix/api/cloudvault.cjs',
    '../src/blocks/aeon_matrix/api/index.cjs',
    '../src/blocks/aeon_matrix/api/ingest.cjs',
    '../src/blocks/aeon_matrix/api/retrieve.cjs',
    '../src/blocks/aeon_matrix/api/sync.cjs',
    '../src/blocks/council/api/index.cjs',
    '../src/blocks/dashboard/api/audit.js',
    '../src/blocks/dashboard/api/chat-stream.cjs',
    '../src/blocks/dashboard/api/chat.cjs',
    '../src/blocks/dashboard/api/health.js',
    '../src/blocks/dashboard/api/pipeline-metrics.js',
    '../src/blocks/deep_research/api/index.cjs',
    '../src/blocks/files/api/fs/read.js',
    '../src/blocks/files/api/fs/write.js',
    '../src/blocks/files/api/notes.js',
    '../src/blocks/fleet_control/api/hwfit.cjs',
    '../src/blocks/fleet_control/api/missions.cjs',
    '../src/blocks/fleet_control/api/local-status.js',
    '../src/blocks/fleet_control/api/telemetry.js',
    '../src/blocks/master/api/master.cjs',
    '../src/blocks/orion_search/api/orion.cjs',
    '../src/blocks/resume_grader/api/grade-resume.js',
    '../src/blocks/security/api/guardian.cjs',
    '../src/blocks/security/api/security.js',
    '../src/blocks/settings/api/connections.js',
    '../src/blocks/settings/api/connectivity.js',
    '../src/blocks/settings/api/model-scan.js',
    '../src/blocks/settings/api/settings.js',
    '../src/blocks/writer/api/writer.js',
    '../src/blocks/writer/api/writer2.cjs',
  ];
  // Mirror blockHost.cjs signature detection: factory (deps)=>router files
  // must have their RETURNED router mounted — calling them as (app, deps)
  // silently discards the router (found 2026-07-16: /api/research/* 404 on web).
  for (const m of mounts) {
    try {
      const factory = require(m);
      if (typeof factory !== 'function') continue;
      if (typeof factory.use === 'function' && Array.isArray(factory.stack)) {
        app.use('/api', factory);                 // exported a bare router
      } else if (factory.length === 1) {
        const result = factory(deps);             // factory pattern
        if (result && typeof result.use === 'function') app.use('/api', result);
      } else {
        factory(app, deps);                       // plugin pattern
      }
    } catch(e) { console.error('[VERCEL] Static mount error (' + m + '):', e.message); }
  }
};

module.exports = require('../server.cjs');
